services:
  web:
    build: .
    ports:
      - "${PORT:-5000}:5000"
    command: sh -c "sh /app/init.sh"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - HOST=${HOST}
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - bridge_network
    restart: always

  db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - bridge_network

volumes:
  postgres_data:
  
networks:
  bridge_network:
    driver: bridge
